#???????????????????root????????demo????????????
spring:
  datasource:
    username: root
    password: 20021014
    url: jdbc:mysql://localhost:3306/woc?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver

#mybatis??resources?mapper?????xml??
mybatis:
  mapper-locations: classpath:mapper/*.xml

#???8081
server:
  port: 8080
